---
name: CI
on:
  repository_dispatch:
    types: start-example-workflow
    inputs:
      file_path:
        description: file share path is provided
        required: true
        default: '/tmp/abc/619'
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "******** file path is taken as variable from devops
          pipeline*********" 
             echo ${{github.event.client_payload.example-key }}
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
